from datetime import datetime
from typing import Protocol

from backend.src.a_domain.model.trading.signal import TradeSignal


class ISignalRepository(Protocol):
    async def save(self, signal: TradeSignal) -> None: ...
    async def save_batch(self, signals: list[TradeSignal]) -> None: ...
    async def get_by_stock_id(
        self, stock_id: str, start_date: datetime | None = None, limit: int = 10
    ) -> list[TradeSignal]: ...
    async def get_latest(self, limit: int = 50) -> list[TradeSignal]: ...
