from typing import Protocol

from src.a_domain.model.market.stock import Stock


class IWatchlistRepository(Protocol):
    """
    Storage Interface: Manages the persistence of candidate lists.
    This is NOT a crawler; it reads/writes to DB/Cache.
    """

    # --- Bucket A: Technical Watchlist (Computed Offline) ---
    async def get_technical_watchlist(self) -> list[Stock]:
        """Retrieve the 'Cold' list generated by nightly batch."""
        ...

    async def save_technical_watchlist(self, stocks: list[Stock]) -> None:
        """Overwrite the 'Cold' list."""
        ...

    # --- Bucket B: Buzz Watchlist (Collected from Social Media) ---
    async def get_buzz_watchlist(self) -> list[tuple[Stock, str]]:
        """
        Retrieve the 'Hot' list stored in DB.
        Returns: List of (Stock, Note/Reason)
        """
        ...

    async def save_buzz_watchlist(self, stocks: list[Stock], reasons: list[str]) -> None:
        """
        Update the 'Hot' list in DB.
        """
        ...

    # --- Utilities ---
    async def get_stocks_by_ids(self, stock_ids: list[str]) -> list[Stock]:
        """Helper to hydrate Stock entities."""
        ...
