from typing import Protocol

from backend.src.a_domain.model.market.stock import Stock


class IWatchlistRepository(Protocol):
    async def get_technical_watchlist(self) -> list[Stock]: ...
    async def save_technical_watchlist(self, stocks: list[Stock]) -> None: ...
    async def get_buzz_watchlist(self) -> list[tuple[Stock, str]]: ...
    async def save_buzz_watchlist(self, stocks: list[Stock], reasons: list[str]) -> None: ...
    async def get_stocks_by_ids(self, stock_ids: list[str]) -> list[Stock]: ...
