from typing import Protocol


class ILoggingProvider(Protocol):
    def info(self, message: str): ...
    def warning(self, message: str): ...
    def debug(self, message: str): ...
    def critical(self, message: str): ...
    def error(self, message: str): ...
    def success(self, message: str): ...
    def trace(self, message: str): ...
    def exception(self, message: str): ...
